ALTER TABLE users
    ADD COLUMN found BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE issues
    ADD COLUMN found BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE comments
    ADD COLUMN found BOOLEAN NOT NULL DEFAULT TRUE;
