services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github_spam
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    image: gh-spam-lab:latest
    env_file: .env
    environment:
      DATABASE__URL: postgres://postgres:postgres@postgres:5432/github_spam
      API__BIND: 0.0.0.0:3000
    ports:
      - "3000:3000"
    volumes:
      - ../config:/srv/app/config:ro
      - ../scripts:/srv/app/scripts:ro
    depends_on:
      postgres:
        condition: service_healthy

  collector:
    image: gh-spam-lab:latest
    env_file: .env
    environment:
      DATABASE__URL: postgres://postgres:postgres@postgres:5432/github_spam
    command: ["/usr/local/bin/collector"]
    volumes:
      - ../config:/srv/app/config:ro
      - ../scripts:/srv/app/scripts:ro
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
