apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-spam-lab.fullname" . }}-api
  labels:
    {{- include "github-spam-lab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "github-spam-lab.selectorLabels" . | nindent 4 }}
    component: api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
