[database]
url = "postgresql://postgres:postgres@localhost:5432/github_spam"

[github]
user_agent = "github-spam-lab"
token_ids = ""
token_secrets = ""

[collector]
interval_secs = 30
page_size = 100
run_once = false
fetch_mode = "hybrid"

[broker]
max_inflight = 32
per_repo_inflight = 2
distributed = false
cache_capacity = 5000
cache_ttl_secs = 600
backoff_base_ms = 500
backoff_max_ms = 60000
jitter_frac = 0.2

[api]
bind = "0.0.0.0:3000"

[observability]
metrics_path = "/metrics"
metrics_bind = "0.0.0.0:9091"
