server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_block_duration: 5m
  trace_idle_period: 10s

compactor:
  compaction:
    compacted_block_retention: 24h
  ring:
    kvstore:
      store: inmemory

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

overrides:
  max_traces_per_user: 100000
