name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/github_spam
      TEST_ADMIN_URL: postgres://postgres:postgres@localhost:5432/postgres
      SQLX_OFFLINE: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Start PostgreSQL
        run: docker compose -f docker/docker-compose.yml up -d postgres
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: Run fmt
        run: cargo fmt -- --check
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Run tests
        run: cargo nextest run --all-targets
