name: Helm Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'chart-v*'

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0
      - name: Lint chart
        run: helm lint charts/github-spam-lab
      - name: Package chart
        run: |
          rm -rf dist
          mkdir -p dist
          helm package charts/github-spam-lab --destination dist
          helm repo index dist --url https://shion1305.github.io/gh-spam-analysis-proj/charts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: dist/*.tgz
      - name: Push chart to GitHub Pages
        if: github.ref_type == 'tag'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          destination_dir: charts
          keep_files: true
          publish_branch: gh-pages
