name: Helm Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'chart-v*'

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0
      - name: Lint chart
        run: helm lint charts/github-spam-lab
      - name: Package chart
        run: |
          rm -rf dist
          mkdir -p dist
          helm package charts/github-spam-lab --destination dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: dist/*.tgz
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push chart to GHCR
        run: |
          for chart in dist/*.tgz; do
            helm push "$chart" oci://ghcr.io/${{ github.repository_owner }}/charts;
          done
